= Singleton Design Pattern

Singleton pattern is a design solution where an application wants to have one and only one instance of any class, in all possible scenarios without any exceptional condition. It has been debated long enough in java community regarding possible approaches to make any class singleton. Still, you will find people not satisfied with any solution you give. They cannot be overruled either. In this post, we will discuss some good approaches and will work towards our best possible effort.

Everyone knows how to do singleton. Lets see how to do bill pugh solution:

```java
public class BillPughSingleton {

    private BillPughSingleton() {

    }

    private static class LazyHolder {
        private static final BillPughSingleton INSTANCE = new BillPughSingleton();
    }

    public static BillPughSingleton getInstance() {
        return LazyHolder.INSTANCE;
    }
}
```
From `wikipedia`
The implementation of the idiom relies on the initialization phase of execution within the Java Virtual Machine (JVM) as specified by the Java Language Specification (JLS).[3] When the class Something is loaded by the JVM, the class goes through initialization. Since the class does not have any static variables to initialize, the initialization completes trivially. The static class definition LazyHolder within it is not initialized until the JVM determines that LazyHolder must be executed. The static class LazyHolder is only executed when the static method getInstance is invoked on the class Something, and the first time this happens the JVM will load and initialize the LazyHolder class. The initialization of the LazyHolder class results in static variable INSTANCE being initialized by executing the (private) constructor for the outer class Something. Since the class initialization phase is guaranteed by the JLS to be sequential, i.e., non-concurrent, no further synchronization is required in the static getInstance method during loading and initialization. And since the initialization phase writes the static variable INSTANCE in a sequential operation, all subsequent concurrent invocations of the getInstance will return the same correctly initialized INSTANCE without incurring any additional synchronization overhead.

While the implementation is an efficient thread-safe "singleton" cache without synchronization overhead, and better performing than uncontended synchronization,[4] the idiom can only be used when the construction of Something can be guaranteed to not fail. In most JVM implementations, if construction of Something fails, subsequent attempts to initialize it from the same class-loader will result in a NoClassDefFoundError failure.
== Advantages
- Singletons prevent decoupling by creating inflexible dependencies between classes, thus severely limiting code reuse in larger projects. Using singletons goes against the idea of abstract interfaces, and has negative impact on your ability to write tests (singletons are usually difficult to mock - in the TDD sense :-)).
- Moreover, from my experience, whenever you think "hey, I will ALWAYS need only single instance of this class," you are usually proven wrong in the course of few development iterations, and forced to use abominable hacks (don't let me started) like Multitons.


== Disadvantages

- Misko Hevery, from Google: It’s make unit testing goes crazy :D Singletons are nothing more than global state. Global state makes it so your objects can secretly get hold of things which are not declared in their APIs, and, as a result, Singletons make your APIs into pathological liars.


== implementations in JDK

- ``java.awt.Desktop#getDesktop()``
- ``java.lang.Runtime#getRuntime()``
